Pull rules_java back to 7.9.1
Looks like 7.10.0 has problems on non-macOS platforms:

- bazelbuild/rules_java: Regression with
  @@rules_java//toolchains:bootstrap_runtime_toolchain_type in 7.10.0
  #214
  https://github.com/bazelbuild/rules_java/issues/214

- bazelbuild/rules_java: Rules java upgrade to 7.10.0 causes issues on
  Windows #218
  https://github.com/bazelbuild/rules_java/issues/218

The latter issue seems to match what we're seeing in CI:

- https://github.com/EngFlow/example/actions/runs/10778667925/job/29890522476?pr=339

```txt
ERROR: no such package '@@rules_java~//tools/jdk': BUILD file not found
in directory 'tools/jdk' of external repository @@rules_java~. Add a
BUILD file to a directory to mark it as a package.

ERROR:
/home/engflow/.cache/bazel/_bazel_engflow/9a27675a6850b9fc7b6f4bb1996879a4/external/rules_java~~toolchains~local_jdk/BUILD.bazel:18:10:
no such package '@@rules_java~//tools/jdk': BUILD file not found in
directory 'tools/jdk' of external repository @@rules_java~. Add a BUILD
file to a directory to mark it as a package. and referenced by
'@@rules_java~~toolchains~local_jdk//:bootstrap_runtime_toolchain_definition'
```

Signed-off-by: Mike Bland <mbland@engflow.com>