Fix `bazel test //swift:tests` via Bzlmod ordering
Also removes extra whitespace and blank lines from README.md.

I inadvertently broke Swift builds and tests in #317 because I added a
`bazel_dep()` for `rules_cc` _before_ the one for `apple_support`. This
restores the proper order.

FWIW, building or testing `//swift:tests` remotely still doesn't seem to
work. It hangs on `--config=remote_macos_x64`, and fails on
`--config=remote_linux_x64` with:

```txt
ERROR: .../external/rules_swift~~non_module_deps~build_bazel_rules_swift_local_config/BUILD:9:22:
  in xcode_swift_toolchain rule
  @@rules_swift~~non_module_deps~build_bazel_rules_swift_local_config//:toolchain:

Traceback (most recent call last):
  File ".../external/rules_swift~/swift/internal/xcode_swift_toolchain.bzl",
    line 641, column 21, in _xcode_swift_toolchain_impl
      env = _xcode_env(target_triple = target_triple, xcode_config = xcode_config)
  File ".../external/rules_swift~/swift/internal/xcode_swift_toolchain.bzl",
    line 539, column 34, in _xcode_env
      _bazel_apple_platform(target_triple),
  File ".../external/rules_swift~/swift/internal/xcode_swift_toolchain.bzl",
    line 101, column 34, in _bazel_apple_platform
      return _TRIPLE_OS_TO_PLATFORM[(
Error: key ("linux", "gnu") not found in dictionary

ERROR: .../external/rules_swift~~non_module_deps~build_bazel_rules_swift_local_config/BUILD:9:22:
Analysis of target '@@rules_swift~~non_module_deps~build_bazel_rules_swift_local_config//:toolchain' failed
```