Bump rules_scala to 6.6.0, rules_java to 7.9.1 (#339)
rules_scala v6.6.0 updated all its repo names to include the version
number in the suffix.

- https://github.com/bazelbuild/rules_scala/releases/tag/v6.6.0
- bazelbuild/rules_scala: Use version-aware naming for artifact
  repositories
  https://github.com/bazelbuild/rules_scala/pull/1573

Hence, now all the repos and toolchains are appended with the scala
version suffix.

My next PR will update the module extensions to enable setting our own
Scala version. The intention is to eventually try to contribute these
extensions (and other necessary changes) upstream.

---------

Also, I had to pull rules_java back to 7.9.1 because 7.10.0 has problems 
on non-macOS platforms:

- bazelbuild/rules_java: Regression with
  @@rules_java//toolchains:bootstrap_runtime_toolchain_type in 7.10.0
  https://github.com/bazelbuild/rules_java/issues/214

- bazelbuild/rules_java: Rules java upgrade to 7.10.0 causes issues on
  Windows 
  https://github.com/bazelbuild/rules_java/issues/218

The latter issue seems to match what we're seeing in CI: 

- https://github.com/EngFlow/example/actions/runs/10778667925/job/29890522476?pr=339

```txt
ERROR: no such package '@@rules_java~//tools/jdk': BUILD file not found
in directory 'tools/jdk' of external repository @@rules_java~. Add a
BUILD file to a directory to mark it as a package.

ERROR:
OUTPUT_BASE/external/rules_java~~toolchains~local_jdk/BUILD.bazel:18:10:
no such package '@@rules_java~//tools/jdk': BUILD file not found in
directory 'tools/jdk' of external repository @@rules_java~. Add a BUILD
file to a directory to mark it as a package. and referenced by
'@@rules_java~~toolchains~local_jdk//:bootstrap_runtime_toolchain_definition'
```

---------

Signed-off-by: Mike Bland <mbland@engflow.com>