Update all dependency versions except protobuf
Also introduces the use of maven_install.json with rules_jvm_external to
track JAR dependencies instead of MODULE.bazel.lock.

We can't update protobuf to the latest version, 27.2, because grpc-java
depends on version 23.1 and breaks if we upgrade it:

```
ERROR: .../external/grpc-java~/protobuf/BUILD.bazel:3:13:
  Building external/grpc-java~/protobuf/libprotobuf.jar (6 source files)
  failed: (Exit 1): java failed: error executing Javac command
  (from target @@grpc-java~//protobuf:protobuf)
  external/rules_java~~toolchains~remotejdk21_macos_aarch64/bin/java
  '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED'
  '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ...
  (remaining 19 arguments skipped)
external/grpc-java~/protobuf/src/main/java/io/grpc/protobuf/StatusProto.java:190:
  error: cannot access Builder
        .setCode(status.getCode().value());
        ^
  class file for com.google.protobuf.GeneratedMessageV3$Builder not found
```

Note: Specifying protobuf 27.2 to generate the above also required
adding com.google.j2objc:j2objc-annotations:3.0.0 to the list of maven
artifacts.